### PR TITLE
feat(OR-1797): update Thanos SDK by new specs

### PR DESCRIPTION
**Pull request by 0x6e616d**

### CODE REVIEW

**Comment by boohyung** [comment]
Thank you! Could you check the lint of packages/tokamak/sdk/tasks/deposit-withdraw-erc20.ts?
* hint: `pnpm lint:fix` in sdk

**Comment by 0x6e616d** [comment]
> Thank you! Could you fix the lint of packages/tokamak/sdk/tasks/deposit-withdraw-erc20.ts?
> 
> * hint: `pnpm lint:fix` in sdk

Thank you, I am done

**Comment by boohyung** [comment]
@0x6e616d Could you check the task `deposit-eth`? If I set the amount is 0 or more than 1, It seems the result does not make sense.
* amount is 0: deposit is successful. 
* amount is more than 1: got error "insufficient funds for gas * price + value: address 0x0000000000000000000000000000000000000000 have 1 want 2"

**Comment by 0x6e616d** [comment]
> @0x6e616d Could you check the task `deposit-eth`? If I set the amount is 0 or more than 1, It seems the result does not make sense.
> 
> * amount is 0: deposit is successful.
> * amount is more than 1: got error "insufficient funds for gas * price + value: address 0x0000000000000000000000000000000000000000 have 1 want 2"

I missed the "from" when estimating the deposit ETH transaction, so when calculating, the code used the default address(0x...). By default, this address has 1 ETH, so when we estimate the amount is larger than 1, the estimated code is not functioning properly.

**Pull request merged**
