### PR TITLE
[OR-1789] remove ec2 runner feature

### PR DESCRIPTION
**Pull request by rlgns98kr**
- remove ec2 runner feature

https://github.com/tokamak-network/tokamak-thanos/actions/runs/10279559325
Thank you very much!

### CODE REVIEW

**Comment by 0x6e616d** [comment]
Hi Steven, Do you don't need arm-64 images?

**Comment by rlgns98kr** [comment]
> Hi Steven, Do you don't need arm-64 images?

Yes, I think. Do you need arm-64 images?

**Comment by 0x6e616d** [comment]
> > Hi Steven, Do you don't need arm-64 images?
> 
> Yes, I think. Do you need arm-64 images?

No, just a question

**Comment by rlgns98kr** [comment]
> > > Hi Steven, Do you don't need arm-64 images?
> > 
> > 
> > Yes, I think. Do you need arm-64 images?
> 
> No, just a question

Thank you very much.
Due to incident about AWS billing, we have to remove ARM architecture using AWS EC2.
If you need some ARM Image, I think you can create it in local or, use the previous image in the docker hub.
I'm sorry again about the incident... 🙇🏼‍♂️

**Review by 0x6e616d — APPROVED** [review]
+1

**Pull request merged**
