### PR TITLE
Migration f8143c8cbc4cc0c83922c53f17a1e47280673485

### PR DESCRIPTION
**Pull request by rlgns98kr**
- update Fjord (@nguyenzung The native token feature is not applied)
- resolve e2e (@nguyenzung I commented some code you made about native token feature)
- keep op-bindings (Optimism delete it. But I think there are some many changes and it is not convenient yet. So, I think we can keep op-bindings)
- keep op-chain-ops L2 genesis (Optimism use the scripts/L2Genesis.sol to create l2 genesis. But we have some predeploys in the op-chain-ops. So I think we can keep our version)

Thank you very much!
https://github.com/tokamak-network/tokamak-thanos/commits/migration-f8143c8cbc4cc0c83922c53f17a1e47280673485

### CODE REVIEW

**Comment by 0x6e616d** [comment]
> update Fjord (@nguyenzung The native token feature is not applied)

You mean in the Fjord version, the custom gas token from OP is not applied?

**Comment by rlgns98kr** [comment]
> > update Fjord (@nguyenzung The native token feature is not applied)
> 
> You mean in the Fjord version, the custom gas token from OP is not applied?

No, It is not applied as well!
But I mean that our Native token feature didn't apply in this PR. I follow the Optimism's code (Bridge, CDM, Portal2)

**Comment by ohbyeongmin** [comment]
How do we manage contracts of applied our NativeToken feature?

**Comment by rlgns98kr** [comment]
> How do we manage contracts of applied our NativeToken feature?

https://github.com/tokamak-network/tokamak-thanos/tree/codeReview

It is operating in this branch. But update task will be taken manually. (There are so many conflict with this branch)

**Comment by ohbyeongmin** [comment]
> > How do we manage contracts of applied our NativeToken feature?
> 
> https://github.com/tokamak-network/tokamak-thanos/tree/codeReview
> 
> It is operating in this branch. But update task will be taken manually. (There are so many conflict with this branch)

I understand. thank you!
Do you plan to do version control after the audit?

**Comment by boohyung** [comment]
@rlgns98kr Thank you so much! Please check out the below comments.

1. packages/tokamak/contracts-bedrock/README.md is already updated to our contracts in https://github.com/tokamak-network/tokamak-thanos/pull/202. Could you restore it? Let me update the README file with fjord version after merging this PR.
2. It seems some bindings should be updated. Could you check it once again?

**Comment by rlgns98kr** [comment]
> @rlgns98kr Thank you so much! Please check out the comments.
> 
> 1. packages/tokamak/contracts-bedrock/README.md is already updated to our contracts in [Or 1738 update README of thanos-contracts #202](https://github.com/tokamak-network/tokamak-thanos/pull/202). Could you restore it? Let me update the README file with the Fjord version after merging this PR.
> 2. It seems some bindings should be updated. Could you check it once again?

I think the README.md is updated lots of things. How about updating one more based on Fjord ? (I'm sorry. I think you can share your thoughts)
Can you share updated binding list in your local? I think I have updated all binding files already. If you say about the `uniswapv3factory_more.go`, it had been updated manually in the past. And `faultdisputegame.go` is fixed manullay. because abigen tool does not have the option to exclude user-defined struct.(we have to remove it. because `optimismportal.go` has the type already)

**Comment by boohyung** [comment]
> > @rlgns98kr Thank you so much! Please check out the comments.
> > 
> > 1. packages/tokamak/contracts-bedrock/README.md is already updated to our contracts in [Or 1738 update README of thanos-contracts #202](https://github.com/tokamak-network/tokamak-thanos/pull/202). Could you restore it? Let me update the README file with the Fjord version after merging this PR.
> > 2. It seems some bindings should be updated. Could you check it once again?
> 
> I think the README.md is updated lots of things. How about updating one more based on Fjord ? (I'm sorry. I think you can share your thoughts) Can you share updated binding list in your local? I think I have updated all binding files already. If you say about the `uniswapv3factory_more.go`, it had been updated manually in the past. And `faultdisputegame.go` is fixed manullay. because abigen tool does not have the option to exclude user-defined struct.(we have to remove it. because `optimismportal.go` has the type already)

1. README is already included these contents: directory structure, contracts overview, installation, deployment and static analysis. I think we need to update README for contracts deployed to L1 and L2. Do we need to apply all the contents of OP README?
2. I updated 4 files in my local: faultdisputegame.go, uniswapv3factory_more.go, wnativetoken_more.go, and wnativetoken.go. Now I'm clear on the first two files. The last two files are updated to change the bin code.

**Comment by boohyung** [comment]
> > > > @rlgns98kr Thank you so much! Please check out the comments.
> > > > 
> > > > 1. packages/tokamak/contracts-bedrock/README.md is already updated to our contracts in [Or 1738 update README of thanos-contracts #202](https://github.com/tokamak-network/tokamak-thanos/pull/202). Could you restore it? Let me update the README file with the Fjord version after merging this PR.
> > > > 2. It seems some bindings should be updated. Could you check it once again?
> > > 
> > > 
> > > I think the README.md is updated lots of things. How about updating one more based on Fjord ? (I'm sorry. I think you can share your thoughts) Can you share updated binding list in your local? I think I have updated all binding files already. If you say about the `uniswapv3factory_more.go`, it had been updated manually in the past. And `faultdisputegame.go` is fixed manullay. because abigen tool does not have the option to exclude user-defined struct.(we have to remove it. because `optimismportal.go` has the type already)
> > 
> > 
> > 
> > 1. README is already included these contents: directory structure, contracts overview, installation, deployment and static analysis. I think we need to update it for fault proof contracts deployed to L1 and L2. Do we need to apply all the contents of OP Fjord README?
> > 2. I updated 4 files in my local: faultdisputegame.go, uniswapv3factory_more.go, wnativetoken_more.go, and wnativetoken.go. Now I'm clear on the first two files. The last two files are updated to change the bin code.
> 
> 1. I think it's not important discussion. We can go things we want. What do you prefer? ([changes](https://github.com/tokamak-network/tokamak-thanos/compare/migration-f8143c8cbc4cc0c83922c53f17a1e47280673485...update_README))
> 2. Did you update foundry? If you have updated foundry, Can you share your foundry artifacts of WNativeToken?

Thanks for your answer.

1. I think https://github.com/tokamak-network/tokamak-thanos/commit/0874473aeed1a434ae2574ea1ed88c70e53f6f5e is sufficient for us. 
2. My foundry version is 0.2.0 (63fff3510 2024-08-23T02:30:26.944892000Z). Let me send the foundry artifacts of WNativeToken.

**Comment by rlgns98kr** [comment]
> > > > > @rlgns98kr Thank you so much! Please check out the comments.
> > > > > 
> > > > > 1. packages/tokamak/contracts-bedrock/README.md is already updated to our contracts in [Or 1738 update README of thanos-contracts #202](https://github.com/tokamak-network/tokamak-thanos/pull/202). Could you restore it? Let me update the README file with the Fjord version after merging this PR.
> > > > > 2. It seems some bindings should be updated. Could you check it once again?
> > > > 
> > > > 
> > > > I think the README.md is updated lots of things. How about updating one more based on Fjord ? (I'm sorry. I think you can share your thoughts) Can you share updated binding list in your local? I think I have updated all binding files already. If you say about the `uniswapv3factory_more.go`, it had been updated manually in the past. And `faultdisputegame.go` is fixed manullay. because abigen tool does not have the option to exclude user-defined struct.(we have to remove it. because `optimismportal.go` has the type already)
> > > 
> > > 
> > > 
> > > 1. README is already included these contents: directory structure, contracts overview, installation, deployment and static analysis. I think we need to update it for fault proof contracts deployed to L1 and L2. Do we need to apply all the contents of OP Fjord README?
> > > 2. I updated 4 files in my local: faultdisputegame.go, uniswapv3factory_more.go, wnativetoken_more.go, and wnativetoken.go. Now I'm clear on the first two files. The last two files are updated to change the bin code.
> > 
> > 
> > 
> > 1. I think it's not important discussion. We can go things we want. What do you prefer? ([changes](https://github.com/tokamak-network/tokamak-thanos/compare/migration-f8143c8cbc4cc0c83922c53f17a1e47280673485...update_README))
> > 2. Did you update foundry? If you have updated foundry, Can you share your foundry artifacts of WNativeToken?
> 
> Thanks for your answer.
> 
> 1. I think [0874473](https://github.com/tokamak-network/tokamak-thanos/commit/0874473aeed1a434ae2574ea1ed88c70e53f6f5e) is sufficient for us.
> 2. My foundry version is 0.2.0 (63fff3510 2024-08-23T02:30:26.944892000Z). Let me send the foundry artifacts of WNativeToken.


1. I updated the README.md!

2.
```
{"compiler":{"version":"0.5.17+commit.d19bba13"},"language":"Solidity","output":{"abi":[{"inputs":[{"internalType":"address","name":"src","type":"address","indexed":true},{"internalType":"address","name":"guy","type":"address","indexed":true},{"internalType":"uint256","name":"wad","type":"uint256","indexed":false}],"type":"event","name":"Approval","anonymous":false},{"inputs":[{"internalType":"address","name":"dst","type":"address","indexed":true},{"internalType":"uint256","name":"wad","type":"uint256","indexed":false}],"type":"event","name":"Deposit","anonymous":false},{"inputs":[{"internalType":"address","name":"src","type":"address","indexed":true},{"internalType":"address","name":"dst","type":"address","indexed":true},{"internalType":"uint256","name":"wad","type":"uint256","indexed":false}],"type":"event","name":"Transfer","anonymous":false},{"inputs":[{"internalType":"address","name":"src","type":"address","indexed":true},{"internalType":"uint256","name":"wad","type":"uint256","indexed":false}],"type":"event","name":"Withdrawal","anonymous":false},{"inputs":[],"stateMutability":"payable","type":"fallback"},{"inputs":[{"internalType":"address","name":"","type":"address"},{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function","name":"allowance","outputs":[{"internalType":"uint256","name":"","type":"uint256"}]},{"inputs":[{"internalType":"address","name":"guy","type":"address"},{"internalType":"uint256","name":"wad","type":"uint256"}],"stateMutability":"nonpayable","type":"function","name":"approve","outputs":[{"internalType":"bool","name":"","type":"bool"}]},{"inputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function","name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}]},{"inputs":[],"stateMutability":"view","type":"function","name":"decimals","outputs":[{"internalType":"uint8","name":"","type":"uint8"}]},{"inputs":[],"stateMutability":"payable","type":"function","name":"deposit"},{"inputs":[],"stateMutability":"view","type":"function","name":"name","outputs":[{"internalType":"string","name":"","type":"string"}]},{"inputs":[],"stateMutability":"view","type":"function","name":"symbol","outputs":[{"internalType":"string","name":"","type":"string"}]},{"inputs":[],"stateMutability":"view","type":"function","name":"totalSupply","outputs":[{"internalType":"uint256","name":"","type":"uint256"}]},{"inputs":[{"internalType":"address","name":"dst","type":"address"},{"internalType":"uint256","name":"wad","type":"uint256"}],"stateMutability":"nonpayable","type":"function","name":"transfer","outputs":[{"internalType":"bool","name":"","type":"bool"}]},{"inputs":[{"internalType":"address","name":"src","type":"address"},{"internalType":"address","name":"dst","type":"address"},{"internalType":"uint256","name":"wad","type":"uint256"}],"stateMutability":"nonpayable","type":"function","name":"transferFrom","outputs":[{"internalType":"bool","name":"","type":"bool"}]},{"inputs":[{"internalType":"uint256","name":"wad","type":"uint256"}],"stateMutability":"nonpayable","type":"function","name":"withdraw"}],"devdoc":{"methods":{}},"userdoc":{"methods":{}}},"settings":{"remappings":["@lib-keccak/=lib/lib-keccak/contracts/lib/","@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/","@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/","@openzeppelin/contracts_v3.1.0/=lib/openzeppelin-contracts_v3.1.0/contracts/","@openzeppelin/contracts_v5.0.1/=lib/openzeppelin-contracts_v5.0.1/contracts/","@rari-capital/solmate/=lib/solmate/","@solady-test/=lib/lib-keccak/lib/solady/test/","@solady/=lib/solady/src/","automate/=lib/automate/contracts/","ds-test/=lib/forge-std/lib/ds-test/src/","erc4626-tests/=lib/openzeppelin-contracts_v5.0.1/lib/erc4626-tests/","forge-std/=lib/forge-std/src/","gelato/=lib/automate/contracts/","hardhat/=lib/automate/node_modules/hardhat/","kontrol-cheatcodes/=lib/kontrol-cheatcodes/src/","lib-keccak/=lib/lib-keccak/contracts/","openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/","openzeppelin-contracts/=lib/openzeppelin-contracts/","openzeppelin-contracts_v3.1.0/=lib/openzeppelin-contracts_v3.1.0/contracts/","openzeppelin-contracts_v5.0.1/=lib/openzeppelin-contracts_v5.0.1/","prb-test/=lib/automate/lib/prb-test/src/","prb/-est/=lib/automate/lib/prb-test/src/","safe-contracts/=lib/safe-contracts/contracts/","solady/=lib/solady/","solmate/=lib/solmate/src/"],"optimizer":{"enabled":true,"runs":999999},"compilationTarget":{"src/vendor/WNativeToken.sol":"WNativeToken"},"evmVersion":"istanbul","libraries":{"SignatureChecker":"0x4200000000000000000000000000000000000776"}},"sources":{"src/vendor/WNativeToken.sol":{"keccak256":"0x04c9852e7e051ce560724aed839ceb48b8bc93074d56e3687b52ebd60d46b276","urls":["bzz-raw://0b511053199ca07cc2d2493deaf21c9b504eab3cd40494210cf3b598e0258710","dweb:/ipfs/QmQxzDBWFwJdTef69N47ckfPDHZqaRu7p1QYY9mbpTrpeE"],"license":null}},"version":1}
```
Above data's IPFS hash will be included in the byte code. It is changed the bytecode because we changed remmapping. But we set the bytecode_hash = false in the foundry.yaml, it is forced to include bytecode_hash in the under solc version (0.6.0).

**Review by boohyung — APPROVED** [review]
Thank you so much! LGTM!

**Pull request merged**
