### PR TITLE
[OR-1648] deploy contracts for thanos-sepolia

### PR DESCRIPTION
**Pull request by rlgns98kr**
- deploy contracts for thanos-sepolia

.envrc
```
# RPC for the network to deploy to
export ETH_RPC_URL=

# Sets the deployer's key to match the first default hardhat account
export PRIVATE_KEY=

# Name of the deployed network
export DEPLOYMENT_CONTEXT=thanos-sepolia

# Optional Tenderly details for a simulation link during deployment
export TENDERLY_PROJECT=
export TENDERLY_USERNAME=

export ETHERSCAN_API_KEY=

# Optional create2 salt for deterministic deployment of
# contract implementations
export IMPL_SALT=$(openssl rand -hex 32)

```

command
```
forge script scripts/Deploy.s.sol:Deploy --broadcast --verify --chain-id 11155111 --rpc-url $ETH_RPC_URL --private-key $PRIVATE_KEY --slow

forge script scripts/Deploy.s.sol:Deploy --sig 'sync()' --rpc-url $ETH_RPC_URL # @nguyenzung it makes deployments!
```

Thank you!

### CODE REVIEW

**Comment by rlgns98kr** [comment]
@ohbyeongmin 
I'm sorry. I set the 24m about output period. If you didn't deploy, can you set the 24m as well? 🙇🏻‍♂️🙇🏻‍♂️

**Review by boohyung — APPROVED** [review]
+1
Thank you so much!

**Comment by ohbyeongmin** [comment]
> @ohbyeongmin I'm sorry. I set the 24m about output period. If you didn't deploy, can you set the 24m as well? 🙇🏻‍♂️🙇🏻‍♂️

sure! thank you

**Comment by 0x6e616d** [comment]
You worked too late. Take care of your health! Thank you very much for your hard-working

**Comment by nguyenzung** [comment]
@rlgns98kr Thank you very much, Steven

I remember those commands and did using it to update make devnet-up. It worked for generating deployment files but I got other error. When I recalled the way to config hardhat task, I stopped updating make devnet-up and updated config file. :smile:

**Pull request merged**
