### PR TITLE
Or 1738 update README of thanos-contracts

### PR DESCRIPTION
**Pull request by boohyung**
I have updated README and clean the pkg.
* Update README with Thanos
* Remove unused file
* Rename the path `hardhat-artifacts` to `uniswap-v3-artifacts` & `src/tokamak-contracts` to `src/USDC`

@AaronLee22 @xxeonge I have renamed the directory you developed for clarity. I have finished testing in the devnet after code update and worked well. Please check any potential problems that I missed. Thanks.

### CODE REVIEW

**Comment by xxeonge** [comment]
https://github.com/tokamak-network/tokamak-thanos/blob/main/.github/workflows/slither-check.yml#L70

It seems that the directory name here also needs to be changed! This might be the reason why Slither failed.

**Comment by xxeonge** [comment]
It seems that the directory name here also needs to be changed! This might be the reason why Slither failed.

**Comment by boohyung** [comment]
> https://github.com/tokamak-network/tokamak-thanos/blob/main/.github/workflows/slither-check.yml#L70
> 
> It seems that the directory name here also needs to be changed! This might be the reason why Slither failed. -> src/USDC

Sorry I missed it. Fixed to https://github.com/tokamak-network/tokamak-thanos/pull/202/commits/f10d46b1c151bcf33d9161a3b1ec3e55fe391f33

**Comment by rlgns98kr** [comment]
@boohyung 
Thank you very much, but,
I don't know why you change the path of contracts,,,
We have to update the path after discussion. I think there may be cases where we need to collect and manage tokamak contracts in one place.
And if we decide to update contracts, we have to update other files as well (Deploy.s.sol, storage-snapshot.sh, verify-predeploy-contracts.sh,,, )
So, I think it's great to change path back,,, 🙇🏻‍♂️

**Comment by boohyung** [comment]
> @boohyung Thank you very much, but, I don't know why you change the path of contracts,,, We have to update the path after discussion. I think there may be cases where we need to collect and manage tokamak contracts in one place. So, I think it's great to change path back,,, 🙇🏻‍♂️

Hi @rlgns98kr, Thanks for your opinion. The reason of changing the path is clarity. 
1. There are no other artifacts except the artifacts of UniswapV3 in `hardhat-artifacts`path.
2. I cannot find any reason to use `tokamak-contracts` in `src`path when the package's directory is already named `tokamak/contracts-bedrock`, and we don't have any additional predeploys confirmed yet besides USDC bridge. But I think we need to update as the number of supported predeploys increases and the direction of our on-demand L2 services is finalized. 

Please leave your thought in this. Any ideas or feedback are welcome. Thank you very much.

**Comment by rlgns98kr** [comment]
> > @boohyung Thank you very much, but, I don't know why you change the path of contracts,,, We have to update the path after discussion. I think there may be cases where we need to collect and manage tokamak contracts in one place. So, I think it's great to change path back,,, 🙇🏻‍♂️
> 
> Hi @rlgns98kr, Thanks for your opinion. The reason of changing the path is clarity.
> 
> 1. There are no other artifacts except the artifacts of UniswapV3 in `hardhat-artifacts`path.
> 2. I cannot find any reason to use `tokamak-contracts` in `src`path when the package's directory is already named `tokamak/contracts-bedrock`, and we don't have any additional predeploys confirmed yet besides USDC bridge. But I think we need to update as the number of supported predeploys increases and the direction of our on-demand L2 services is finalized.
> 
> Please leave your thought in this. Any ideas or feedback are welcome. Thank you very much.

Okay, Thank you! 
I understood why you changed the path. I hope that we have a discussion about this kind of change next time.

As you said, currently there is only one usdc bridge, but this can be increased at any time. So, I still think We should use tokamak-contracts path...  🙇🏻‍♂️🙇🏻‍♂️

**Comment by boohyung** [comment]
> > > @boohyung Thank you very much, but, I don't know why you change the path of contracts,,, We have to update the path after discussion. I think there may be cases where we need to collect and manage tokamak contracts in one place. So, I think it's great to change path back,,, 🙇🏻‍♂️
> > 
> > 
> > Hi @rlgns98kr, Thanks for your opinion. The reason of changing the path is clarity.
> > 
> > 1. There are no other artifacts except the artifacts of UniswapV3 in `hardhat-artifacts`path.
> > 2. I cannot find any reason to use `tokamak-contracts` in `src`path when the package's directory is already named `tokamak/contracts-bedrock`, and we don't have any additional predeploys confirmed yet besides USDC bridge. But I think we need to update as the number of supported predeploys increases and the direction of our on-demand L2 services is finalized.
> > 
> > Please leave your thought in this. Any ideas or feedback are welcome. Thank you very much.
> 
> Okay, Thank you! I understood why you changed the path. I hope that we have a discussion about this kind of change next time.
> 
> As you said, currently there is only one usdc bridge, but this can be increased at any time. So, I still think We should use tokamak-contracts path... 🙇🏻‍♂️🙇🏻‍♂️ But I think the changes of hardhat-artifacts is great. I think we can keep your version!

Thanks for your opinion. Fixed to https://github.com/tokamak-network/tokamak-thanos/pull/202/commits/125608dfd5f2e9167c90e9640fd70b2e19401c23

**Review by rlgns98kr — APPROVED** [review]
Thank you very much! 🙇🏻‍♂️🙇🏻‍♂️

**Pull request merged**
