### PR TITLE
OR-1525 update e2e-test for bridge

### PR DESCRIPTION
**Pull request by nguyenzung**
Update e2e test for bridges: add withdrawal cases

Thank you!

### CODE REVIEW

**Comment by rlgns98kr** [comment]
@nguyenzung 
Thank you very much!
I think we can use same name. I recommend WNativeToken instead of L1Token,,, 🙇🏼‍♂️ Is it weird a little?,,, I'm sorry,,, 🥹🥲

**Comment by nguyenzung** [comment]
> @nguyenzung Thank you very much! I think we can use same name. I recommend WNativeToken instead of L1Token,,, 🙇🏼‍♂️ Is it weird a little?,,, I'm sorry,,, 🥹🥲

Thank you very much, Steven

Let me update it!

**Comment by rlgns98kr** [comment]
> > @nguyenzung Thank you very much! I think we can use same name. I recommend WNativeToken instead of L1Token,,, 🙇🏼‍♂️ Is it weird a little?,,, I'm sorry,,, 🥹🥲
> 
> Thank you very much, Steven
> 
> Let me update it!
> 
> @rlgns98kr I just checked it again. L1Token is used for an ERC20 token when testing deposit/withdraw ERC20. It is not WNativeToken

LEGACY_ERC20_NATIVE_TOKEN = 0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000;
-> It's is just for legacy support
WNativeToken                  = "0x4200000000000000000000000000000000000006"
-> It's is for WETH9 (to use uniswap,,, etc...)

I think the name is weird a little. I'm sorry again. I tried to change the name of ETH to NativeToken...

In the test code, It's used to check about erc20 dep/with as you said. But I think if we use WNativeToken contract as ERC20 for that, we have to use same naming...🙇🏼‍♂️

**Comment by rlgns98kr** [comment]
I'm sorry,,, Brave,,, Please change it one more 🥹🥺
wNativeToken -> WNativeToken
And l1Address is a very great idea! It makes to reduce confusion!

**Review by rlgns98kr — APPROVED** [review]
Thank you very much! 🙇🏻‍♂️❤️❤️

**Pull request merged**
