### PR TITLE
feat(sdk): default contracts portal l1 contracts

### PR DESCRIPTION
**Pull request by 0x6e616d**
In case we use the devnet network, when initing the OptimismPortal by using SDK, these contracts in `portal.contracts.l1.<contract_name>` are undefined.

Because we are looping `addresses.l1` to get the contract name, and value, then override these contracts by `opts`
Ref: https://github.com/tokamak-network/tokamak-thanos/blob/main/packages/tokamak/sdk/src/utils/contracts.ts#L253

Example:
```js
const optimismPortal = new thanosSDK.Portals({
    l1ChainId,
    l2ChainId,
    l1SignerOrProvider: l1Wallet,
    l2SignerOrProvider: l2Wallet,
    contracts: {
      l1: {
        AddressManager: '0xA8f606cE44B7E688Ed61a703264A22931A8fdf22',
        L1CrossDomainMessenger: '0x374f7c5D6dDbAcf5c2F403B5Bfd8461585fd0841',
        L1StandardBridge: '0xE720f60538fdAEfEdb4DB00266021b45ffF02b04',
        OptimismPortal: '0x309972363B4EA329982A3CD9193e300b6d4eC0A7',
        L2OutputOracle: '0x453e9c42AfB81CAb455b5aC1CD855061fb14B829'
      }
    }
  })

console.log(`L1StandardBridge address: ${optimismPortal.contracts.l1.L1StandardBridge`)
// L1StandardBridge address: undefined
```

=> I use the existing function `getAllOEContracts` and remove the redundant function: `getPortalsContracts`

### CODE REVIEW

**Comment by nguyenzung** [comment]
Thank you for your opinion, Nam
I think in context of Portal, we only need OptimismPortal and L2OutputOracle to init.

**Review by boohyung — APPROVED** [review]
+1
Thank you very much Nam!

**Comment by 0x6e616d** [comment]
Just in case I want to deposit the native token by using `onApproveAndCall` function, via L1StandardBridge. And use OptimismPortal to check the status of this transaction.

What do you think about that case @nguyenzung @ohbyeongmin

**Comment by nguyenzung** [comment]
> Just in case I want to deposit the native token by using `onApproveAndCall` function, via L1StandardBridge. And use OptimismPortal to check the status of this transaction.
> 
> What do you think about that case @nguyenzung @ohbyeongmin
> 
> ```js
> const approveTx = await l2NativeTokenContractInL1.approveAndCall(
>     optimismPortal.contracts.l1.L1StandardBridge.address, // need to put the L1StandardBridge address here
>     depositAmount,
>     depositData
>   )
>   const approveTxReceipt = await approveTx.wait()
>   console.log(`Approve and call transaction: ${approveTxReceipt.transactionHash}`)
> 
> 
>   const relayTxHash = await optimismPortal.waitingDepositTransactionRelayed(
>     approveTxReceipt,
>     {}
>   )
>   if (!relayTxHash) {
>     throw new Error("Relay tx hash empty")
>   }
> ```

In this case, I think we only need deposit Transaction Hash.

**Comment by ohbyeongmin** [comment]
> Just in case I want to deposit the native token by using `onApproveAndCall` function, via L1StandardBridge. And use OptimismPortal to check the status of this transaction.
> 
> What do you think about that case @nguyenzung @ohbyeongmin
> 
> ```js
> const approveTx = await l2NativeTokenContractInL1.approveAndCall(
>     optimismPortal.contracts.l1.L1StandardBridge.address, // need to put the L1StandardBridge address here
>     depositAmount,
>     depositData
>   )
>   const approveTxReceipt = await approveTx.wait()
>   console.log(`Approve and call transaction: ${approveTxReceipt.transactionHash}`)
> 
> 
>   const relayTxHash = await optimismPortal.waitingDepositTransactionRelayed(
>     approveTxReceipt,
>     {}
>   )
>   if (!relayTxHash) {
>     throw new Error("Relay tx hash empty")
>   }
> ```

CrossChainMessenger has the address L1StandardBridge. [code link](https://github.com/tokamak-network/tokamak-thanos/blob/1cc9266bf46a2b5045aea18e499992fe9b3114db/packages/tokamak/sdk/src/cross-chain-messenger.ts#L186)
What do you think?

**Comment by 0x6e616d** [comment]
> > Just in case I want to deposit the native token by using `onApproveAndCall` function, via L1StandardBridge. And use OptimismPortal to check the status of this transaction.
> > What do you think about that case @nguyenzung @ohbyeongmin
> > ```js
> > const approveTx = await l2NativeTokenContractInL1.approveAndCall(
> >     optimismPortal.contracts.l1.L1StandardBridge.address, // need to put the L1StandardBridge address here
> >     depositAmount,
> >     depositData
> >   )
> >   const approveTxReceipt = await approveTx.wait()
> >   console.log(`Approve and call transaction: ${approveTxReceipt.transactionHash}`)
> > 
> > 
> >   const relayTxHash = await optimismPortal.waitingDepositTransactionRelayed(
> >     approveTxReceipt,
> >     {}
> >   )
> >   if (!relayTxHash) {
> >     throw new Error("Relay tx hash empty")
> >   }
> > ```
> 
> In this case, I think we only need deposit Transaction Hash.

But we must have the `L1StandardBridge` to approve TON via this address 😄 Just in case we only init Portal instance, not have `CrossDomainMessenger` instance.

@nguyenzung @ohbyeongmin

**Comment by 0x6e616d** [comment]
> I am sorry, I think my explanation was short. Basically, Portal supports:
> 
> * waitingDepositTransactionRelayedUsingL1Tx(depositHash)
> * calculateRelayedDepositTxID
> 
> It means we can init Portal with OptimismPortal and L2OutputOracle addresses and it works for any deposit transaction Hash even if we make transaction with L1StandardBridge or L1CrossDomainMessenger. Right now, it supports for one deposit event for one deposit transaction

I know it, but maybe misunderstanding here:

For example, I want to deposit TON via `L1StandardBridge` contract directly by using `approveAndCall` function => I **must have `L1StandardBridge` address for approving TON**.

I can init the `CrossDomainMessenger` instance and get the `L1StandardBridge` address => This is a normal way
But in my code, there is an existing `Portal` instance. How can I get the `L1StandardBridge`?

**Comment by nguyenzung** [comment]
> > I am sorry, I think my explanation was short. Basically, Portal supports:
> > 
> > * waitingDepositTransactionRelayedUsingL1Tx(depositHash)
> > * calculateRelayedDepositTxID
> > 
> > It means we can init Portal with OptimismPortal and L2OutputOracle addresses and it works for any deposit transaction Hash even if we make transaction with L1StandardBridge or L1CrossDomainMessenger. Right now, it supports for one deposit event for one deposit transaction
> 
> I know it, but maybe we have a misunderstanding here:
> 
> For example, I want to deposit TON via `L1StandardBridge` contract directly by using `approveAndCall` function => I **must have `L1StandardBridge` address for approving TON**.
> 
> I can init the `CrossDomainMessenger` instance and get the `L1StandardBridge` address => This is a normal way But in my code, there is an existing `Portal` instance. How can I get the `L1StandardBridge` without initing a `CrossDomainMessenger` instance?

Oh, I am sorry. I understood in another way. 

In my personal opinion, Portal 's SDK does not need to know other addresses like StandardBridge, CDM. Actually, we can make more contracts like StandardBridge or CDM.

**Comment by 0x6e616d** [comment]
So I think I'll close this PR

**Pull request closed without merging**
