### PR TITLE
Or 1796 native token update native token based on the new spec

### PR DESCRIPTION
**Pull request by nguyenzung**
Merge to the branch codeReview for internal audit

Test: there are e2e-tests for all cases deposit/withdraw Native token, ETH, ERC20 in the folder op-e2e/e2e-dep-with
- cd op-e2e
- OP_TESTLOG_DISABLE_COLOR=true OP_E2E_CANNON_ENABLED=false OP_E2E_DISABLE_PARALLEL=false gotestsum --format=standard-verbose -- -timeout=25m -parallel=16 -failfast ./...

Thank you very much!

### CODE REVIEW

**Comment by boohyung** [comment]
@nguyenzung Thank you so much. Could you look at the checklist page and mark the modified functions as complete? This version seems not equal to the specification (e.g., `finalizeBridgeNativeToken` function in L1StandardBridge is not here.)
* checklist page: https://www.notion.so/tokamak/Checklist-for-update-codebase-following-finalized-specification-2f9e22931a5e48c7bc5fd4f4f8178799?pvs=4

**Comment by nguyenzung** [comment]
> @nguyenzung Thank you so much. Could you look at the checklist page and mark the modified functions as complete?
> 
> * checklist page: https://www.notion.so/tokamak/Checklist-for-update-codebase-following-finalized-specification-2f9e22931a5e48c7bc5fd4f4f8178799?pvs=4

@boohyung Thank you very much. I updated the checklist

**Comment by nguyenzung** [comment]
> @nguyenzung Thank you so much. Could you look at the checklist page and mark the modified functions as complete?
> 
> * checklist page: https://www.notion.so/tokamak/Checklist-for-update-codebase-following-finalized-specification-2f9e22931a5e48c7bc5fd4f4f8178799?pvs=4

@boohyung Thank you very much. I updated the checklist

**Comment by boohyung** [comment]
> > @nguyenzung Thank you so much. Could you look at the checklist page and mark the modified functions as complete?
> > 
> > * checklist page: https://www.notion.so/tokamak/Checklist-for-update-codebase-following-finalized-specification-2f9e22931a5e48c7bc5fd4f4f8178799?pvs=4
> 
> @boohyung Thank you very much. I updated the checklist

I just found all items are checked. Thank you!

**Comment by boohyung** [comment]
@nguyenzung Why don't you restore `depositETH`, `depositETHTo`, `depositERC20`, `depositERC20To` in L1StanardBridge? We used in these functions in our SDK. (e.g., https://github.com/tokamak-network/tokamak-thanos/blob/main/packages/tokamak/sdk/tasks/deposit-withdraw-eth.ts#L148)

**Comment by nguyenzung** [comment]
> @nguyenzung Why don't you restore `depositETH`, `depositETHTo`, `depositERC20`, `depositERC20To` in L1StanardBridge? We used these functions in our SDK. (e.g., https://github.com/tokamak-network/tokamak-thanos/blob/main/packages/tokamak/sdk/tasks/deposit-withdraw-eth.ts#L148)

Those functions are for backward compatibility. I think we should remove it and update the functions that are used in the SDK. What do you think?

**Comment by nguyenzung** [comment]
> > @nguyenzung Why don't you restore `depositETH`, `depositETHTo`, `depositERC20`, `depositERC20To` in L1StanardBridge? We used these functions in our SDK. (e.g., https://github.com/tokamak-network/tokamak-thanos/blob/main/packages/tokamak/sdk/tasks/deposit-withdraw-eth.ts#L148)
> 
> Those functions are for backward compatibility. Optimism designed function like bridgeETH, bridgeERC20 to replace deposit* functions. Basically, there will be no concept about deposit and withdraw, just bridging. So I think we should remove it and update the functions that are used in the SDK. What do you think?

**Comment by boohyung** [comment]
> > @nguyenzung Why don't you restore `depositETH`, `depositETHTo`, `depositERC20`, `depositERC20To` in L1StanardBridge? We used these functions in our SDK. (e.g., https://github.com/tokamak-network/tokamak-thanos/blob/main/packages/tokamak/sdk/tasks/deposit-withdraw-eth.ts#L148)
> 
> Those functions are for backward compatibility. Optimism designed function like bridgeETH, bridgeERC20 to replace deposit* functions. Basically, there will be no concept about deposit and withdraw, just bridging. So I think we should remove it and update the functions that are used in the SDK. What do you think?

Let me look at the SDK code after today's call and let you know my thoughts. Thanks!

**Comment by nguyenzung** [comment]
> Thank you so much! I have checked all tests have passed.

Maybe @boohyung  @0x6e616d are working in the same task for updating the SDK

**Comment by 0x6e616d** [comment]
> > Thank you so much! I have checked all tests have passed.
> 
> Maybe @boohyung @0x6e616d are working in the same task for updating the SDK

Hi @boohyung @nguyenzung  Yes, I am working on modifying the SDK based on your changes.

**Comment by boohyung** [comment]
> > > Thank you so much! I have checked all tests have passed.
> > 
> > 
> > Maybe @boohyung @0x6e616d are working in the same task for updating the SDK
> 
> Hi @boohyung @nguyenzung Yes, I am working on modifying the SDK based on your changes.

Hi @0x6e616d Sorry I missed it. When will you finish your work? (jira ticket: OR-1797) We have a plan to start internal code review from next monday to next friday (5 business days) and we need to finish modifying SDK before starting internal code review.

**Comment by boohyung** [comment]
@nguyenzung It seems we did not have e2e test for withdaw ETH and withdraw ERC20 in the op-e2e package. Please let me know if I was wrong. And I think we should provide e2e test example for internal code review as hardhat tasks in sdk or test example in op-e2e. What do you think?

**Comment by 0x6e616d** [comment]
@boohyung It will be done today

**Comment by nguyenzung** [comment]
> @nguyenzung It seems we did not have an e2e test for withdaw ETH and withdraw ERC20 (not L2 native token) in the op-e2e package. Please let me know if I am wrong. And I think we should provide e2e test examples for internal code review as hardhat tasks in sdk or test examples in op-e2e. What do you think?

I think the name of the test should be updated. Actually, we are test both  withdrawal feature in function 
- TestETHBridgeDeposits
- TestERC20BridgeDeposits

**Comment by boohyung** [comment]
> > @nguyenzung It seems we did not have an e2e test for withdaw ETH and withdraw ERC20 (not L2 native token) in the op-e2e package. Please let me know if I am wrong. And I think we should provide e2e test examples for internal code review as hardhat tasks in sdk or test examples in op-e2e. What do you think?
> 
> I think the name of the test should be updated. Actually, we are test both deposit and withdrawal (by using L2StandardBridge) features in the function
> 
> * TestETHBridgeDeposits
> * TestERC20BridgeDeposits

Thank you. I found them with your help. I think we don't have to change the name of the test function.

**Pull request merged**
