### PR TITLE
Or 1592 titan cannon update system config

### PR DESCRIPTION
**Pull request by nguyenzung**
- add nativeTokenAddress to SystemConfig

Thank you!

### CODE REVIEW

**Comment by rlgns98kr** [comment]
I'm checking the thanos-ci-builder!
I'm sorry.

**Comment by nguyenzung** [comment]
> I'm checking the thanos-ci-builder! I'm sorry.

Thank you very much, Steven!

**Review by boohyung — APPROVED** [review]
the changes are LGTM. Thank you so much!

By the way I have one question. Where do we use Multichain.s.sol? Do you have a plan to use it to upgrade L1 contracts? If yes, let me restore it https://github.com/tokamak-network/tokamak-thanos/pull/155.

**Comment by nguyenzung** [comment]
> the changes are LGTM. Thank you so much!
> 
> @nguyenzung @rlgns98kr By the way I have one question. Where do we use Multichain.s.sol? Do you have a plan to use it to upgrade L1 contracts? If yes, let me restore it #155.

We have other way to upgrade smart contracts. But I am not sure about Multichain.s.sol. I am preparing for tomorrow seminar. I will check it in more detail after the seminar. 

What is your opinion about Multichain.s.sol? @rlgns98kr

**Comment by rlgns98kr** [comment]
In fact, I don't know well. Can you check what is it, @boohyung ?

**Comment by rlgns98kr** [comment]
@nguyenzung 
Will you update SB, CDM, Portal to use SystemConfig.nativetoken as well?

**Comment by boohyung** [comment]
> In fact, I don't know well. Can you check what is it, @boohyung ?

Sure. Let me take a look at it!

**Comment by nguyenzung** [comment]
> @nguyenzung Will you update SB, CDM, Portal to use SystemConfig.nativetoken as well?

I had the same idea. But it could takes more gas because it have to make a staticcall to get nativeTokenAddress. What do you think? @rlgns98kr

**Comment by rlgns98kr** [comment]
@nguyenzung 
Even if we create the function as a view, does it still consume gas?

**Comment by nguyenzung** [comment]
> @nguyenzung Even if we create the function as a view, does it still consume gas?

Yes it cost gas if be called from not view and not pure function. It still needs to load bytecode of System Config, construct a new EVM static context, execute some instructions and return result.

EVM opcodes: https://www.evm.codes/

When we call a view function in our terminal or web, it is not transactions so does not cost any gas. If being called in a transaction, it still costs gas

**Comment by rlgns98kr** [comment]
@nguyenzung 
Thank you for your kind answer!
I think it is okay the value is about 200(Call + SLOAD ?)! ❤️🙇🏻‍♂️
I think we have to tell to bridge team to use accesslist.

**Comment by boohyung** [comment]
@rlgns98kr @nguyenzung Multichain.s.sol is now dead script and it is for upgrading the L1 contracts in devnet. not production. and it was removed in https://github.com/ethereum-optimism/optimism/commit/122f041dac6cf61073d5896cc5dd03c98d23f4b1. 

So we don't care about it. Let me check if there's another dead script in applying Ecotone. Thank you so much!

**Comment by nguyenzung** [comment]
> @nguyenzung Thank you for your kind answer! I think it is okay the value is about 200(Call + SLOAD ?)! ❤️🙇🏻‍♂️ I think we have to tell to bridge team to use accesslist.

It seems great! Let me have a deeper look on it on the next day or we can discuss more on the seminar. 
Actually, to get the nativeTokenAddress, it has more instructions than StaticCall + SLOAD. Using accesslist is really interesting and potential way in our case

**Review by rlgns98kr — APPROVED** [review]
Thank you very much, Brave! 🙇🏻‍♂️

**Pull request merged**
