### PR TITLE
fix(portal-contract): wrong 'from' when depositing from the contract through Portal.onApprove function

### PR DESCRIPTION
**Pull request by 0x6e616d**
Resolved: [External Issue #39](https://github.com/sherlock-audit/2024-08-tokamak-network-judging/issues/39)

I added a new test for these changes but removed because it only worked with `forge test --match-contract OptimismPortal2_Test`. 

With the contract `DeploymentSummaryFaultProofs_TestOptimismPortal` that is using `Kontrol`, `vm.startPrank`  didn't work with `l2NativeToken.mint(value)` or `l2NativeToken.approveAndCall`: [issue](https://github.com/runtimeverification/kontrol/issues/190)

So we can add the test later. My test
```solidity
/// @dev Tests that `onApprove` succeeds for an EOA.
    function testFuzz_onApprove_eoa_succeeds(
        address _to,
        uint32 _gasLimit,
        uint256 _value,
        uint256 _mint,
        bool _isCreation,
        bytes memory _data
    )
    external
    {
        _gasLimit = uint32(
            bound(
                _gasLimit,
                optimismPortal2.minimumGasLimit(uint32(_data.length)),
                systemConfig.resourceConfig().maxResourceLimit
            )
        );
        if (_isCreation) _to = address(0);

        vm.startPrank(depositor, depositor);
        l2NativeToken.faucet(_value);

        bytes memory onApproveData = abi.encodePacked(_to, _mint, _gasLimit, _data);

        // EOA emulation
        vm.expectEmit(true, true, true, true);
        emit TransactionDeposited(depositor, _to, 0, onApproveData);

        l2NativeToken.approveAndCall(address(optimismPortal2), _value, onApproveData);
    }

    /// @dev Tests that `onApprove` succeeds for a contract.
    function testFuzz_onApprove_contract_succeeds(
        address _to,
        uint32 _gasLimit,
        uint256 _value,
        uint256 _mint,
        bool _isCreation,
        bytes memory _data
    )
    external
    {
        _gasLimit = uint32(
            bound(
                _gasLimit,
                optimismPortal2.minimumGasLimit(uint32(_data.length)),
                systemConfig.resourceConfig().maxResourceLimit
            )
        );
        if (_isCreation) _to = address(0);

        vm.startPrank(address(this));
        l2NativeToken.faucet(_value);

        bytes memory onApproveData = abi.encodePacked(_to, _mint, _gasLimit, _data);

        vm.expectEmit(true, true, true, false);
        emit TransactionDeposited(AddressAliasHelper.applyL1ToL2Alias(address(this)), _to, 0, hex"");

        l2NativeToken.approveAndCall(address(optimismPortal2), _value, onApproveData);
    }
```

### CODE REVIEW

**Review by rlgns98kr — APPROVED** [review]
Thank you very much, Nam! 
I think we should not merge this yet, shouldn't we?

**Comment by 0x6e616d** [comment]
> Thank you very much, Nam! I think we should not merge this yet, shouldn't we?

I think we can submit PR to the external audit team then merging when finalize the audit.

**Comment by theo-learner** [comment]
@tokamak-network/layer2-core I will submit the commit link to Sherlock. Do we need an additional review of this code? If you need it, please let me know by tomorrow.

**Comment by nguyenzung** [comment]
I think the code needs to be updated base on the commit c3a2bd6f768f0719a63fa1e0231eaae1d42f9e24

**Comment by theo-learner** [comment]
> I think the code needs to be updated base on the commit [c3a2bd6](https://github.com/tokamak-network/tokamak-thanos/commit/c3a2bd6f768f0719a63fa1e0231eaae1d42f9e24)

Good point. Could you rebase it? @0x6e616d

**Comment by 0x6e616d** [comment]
> > I think the code needs to be updated base on the commit [c3a2bd6](https://github.com/tokamak-network/tokamak-thanos/commit/c3a2bd6f768f0719a63fa1e0231eaae1d42f9e24)
> 
> Good point. Could you rebase it? @0x6e616d

Rebased, thank you @nguyenzung @theo-learner

**Comment by 0x6e616d** [comment]
> I created the new branch for submitting fixed PR. Could you change the base branch to fix-review(https://github.com/tokamak-network/tokamak-thanos/tree/fix-review)?

Done, thank you

**Comment by 0x6e616d** [comment]
> I created the new branch for submitting fixed PR. Could you change the base branch to fix-review(https://github.com/tokamak-network/tokamak-thanos/tree/fix-review)?

Done, thank youuu

**Pull request merged**
