### PR TITLE
OR-1520 Merge the Ecotone spec to Thanos

### PR DESCRIPTION
**Pull request by boohyung**
I have changed Optimism's base protocol version from Canyon to Ecotone.
* op-node, op-batcher, op-proposer: [v1.7.0](https://github.com/ethereum-optimism/optimism/tree/v1.7.0)
* op-geth: [v1.101308.2](https://github.com/ethereum-optimism/op-geth/tree/v1.101308.2)
* this PR included 2 network upgrade of Optimism: [Delta](https://specs.optimism.io/protocol/superchain-upgrades.html#delta), [Ecotone](https://specs.optimism.io/protocol/superchain-upgrades.html#ecotone)

Note. We can run the network and test bridge transactions in the devnet. During the withdrawal, the L2 transaction is created correctly. but I am currently investigating that there is an issue where it gets stuck on `wait()`

### CODE REVIEW

**Comment by 0x6e616d** [comment]
@boohyung Remember that need to generate the `bindings` folder

**Comment by boohyung** [comment]
> @boohyung Remember that need to generate the `bindings` folder

I have already updated bindings to https://github.com/tokamak-network/tokamak-thanos/pull/155/commits/287a0de43b4b3951705ef37a6c0724cac912a5b3. you said that `bindings` is related to https://github.com/tokamak-network/tokamak-thanos/actions/runs/9015129810/job/24769152028?pr=155?

**Comment by 0x6e616d** [comment]
> Details

I saw the error on the lint ci,
https://github.com/tokamak-network/tokamak-thanos/actions/runs/9030207897/job/24814009723?pr=155

So I think we should regenerate the bindings folder :D

**Comment by boohyung** [comment]
> > Details
> 
> I saw the error on the lint ci, https://github.com/tokamak-network/tokamak-thanos/actions/runs/9030207897/job/24814009723?pr=155
> 
> So I think we should regenerate the bindings folder :D



> > Details
> 
> I saw the error on the lint ci, https://github.com/tokamak-network/tokamak-thanos/actions/runs/9030207897/job/24814009723?pr=155
> 
> So I think we should regenerate the bindings folder :D



> > Details
> 
> I saw the error on the lint ci, https://github.com/tokamak-network/tokamak-thanos/actions/runs/9030207897/job/24814009723?pr=155
> 
> So I think we should regenerate the bindings folder :D

Ok. I know that so I'm updating binding now. Let me fix the golangCI-lint error.

**Pull request merged**
