### PR TITLE
[OR-1623] fix ci for publish docker pakcages

### PR DESCRIPTION
**Pull request by rlgns98kr**
- fix ci for publish docker pakcages
failed CI: https://github.com/tokamak-network/tokamak-thanos/actions/runs/9220157195

Thank you! 🙇🏼‍♂️

### CODE REVIEW

**Comment by nguyenzung** [comment]
Hi Steven,
Could you explain about the root cause and how you resolve it? :bow:

**Comment by 0x6e616d** [comment]
> Hi Steven, Could you explain about the root cause and 
how you resolve it? 🙇


I guess this error is related to:

Screenshot 2024-05-24 at 14 43 13

**Comment by 0x6e616d** [comment]
Ref to: https://github.com/ethereum-optimism/optimism/blob/develop/ops/docker/Dockerfile.packages#L20C50-L20C81

**Review by 0x6e616d — APPROVED** [review]
Thank you!

**Comment by rlgns98kr** [comment]
> Hi Steven, Could you explain about the root cause and how you resolve it? 🙇

Sure, I'm sorry for my missing!
I don't know about this.
But when I tested to build docker in my local, I become to know about the difference of the pnpm-lock.yaml file. There is `pnpmfileChecksum: vipskp6rjsbh4jjdio2kmcz6ye` in our repo. But in the docker build, there is no this line. So, I checked about this line. I become to know that it is created by `.pnpmfile.cjs`. And I found there is no `.pnpmfile.cjs` in the dockerfile in our packages.

I want to know about this file more!

**Comment by nguyenzung** [comment]
> > Hi Steven, Could you explain about the root cause and how you resolve it? 🙇
> 
> Sure, I'm sorry for my missing! I don't know about this. But when I tested to build docker in my local, I become to know about the difference of the pnpm-lock.yaml file. There is `pnpmfileChecksum: vipskp6rjsbh4jjdio2kmcz6ye` in our repo. But in the docker build, there is no this line. So, I checked about this line. I become to know that it is created by `.pnpmfile.cjs`. And I found there is no `.pnpmfile.cjs` in the dockerfile in our packages.
> 
> I want to know about this file more!

Thank you very much, Steven! :heart:

**Pull request merged**
